DECLARE
D VARCHAR2(3):=TO_CHAR(SYSDATE,'DY');
BEGIN
IF D='SAT' THEN
  DBMS_OUTPUT.PUT_LINE('ENJOY YOUR WEEKEND');
ELSIF D='SUN' THEN
 DBMS_OUTPUT.PUT_LINE('ENJOY YOUR WEEKEND');
ELSE
 DBMS_OUTPUT.PUT_LINE('HAVE A NICE DAY');
END IF;
END;